import prisma from '../lib/db'

async function testBlogAutomationSystem() {
  console.log('🧪 Testing Blog Automation System...\n')

  try {
    // Test 1: Check database connection and BlogPost model
    console.log('📊 Test 1: Database connection and schema...')
    const blogPostCount = await prisma.blogPost.count()
    console.log(`✅ Database connected. Total blog posts: ${blogPostCount}`)
    
    // Check if we have the new fields
    const samplePost = await prisma.blogPost.findFirst({
      select: {
        id: true,
        title: true,
        aiGenerated: true,
        sourceUrl: true
      }
    })
    
    if (samplePost) {
      console.log(`✅ Schema updated. Sample post has aiGenerated: ${samplePost.aiGenerated}, sourceUrl: ${samplePost.sourceUrl || 'null'}`)
    } else {
      console.log('ℹ️ No blog posts found in database')
    }

    // Test 2: Test RSS feed API endpoint
    console.log('\n📰 Test 2: Testing RSS feed API...')
    try {
      const response = await fetch('http://localhost:3000/api/rss/feeds')
      if (response.ok) {
        const data = await response.json()
        console.log(`✅ RSS feeds API working. Found ${data.feeds?.length || 0} feeds`)
      } else {
        console.log(`⚠️ RSS feeds API returned status: ${response.status}`)
      }
    } catch (error) {
      console.log(`⚠️ RSS feeds API test skipped (server may not be running): ${error}`)
    }

    // Test 3: Test blog automation stats API
    console.log('\n📈 Test 3: Testing blog automation stats API...')
    try {
      const response = await fetch('http://localhost:3000/api/blog-automation/stats')
      if (response.ok) {
        const data = await response.json()
        console.log(`✅ Blog automation stats API working. Total generated: ${data.total}`)
        console.log(`   Published: ${data.published}, Drafts: ${data.draft}`)
        console.log(`   Average quality: ${data.averageQuality}%`)
      } else {
        console.log(`⚠️ Blog automation stats API returned status: ${response.status}`)
      }
    } catch (error) {
      console.log(`⚠️ Blog automation stats API test skipped (server may not be running): ${error}`)
    }

    // Test 4: Test generated content API
    console.log('\n🤖 Test 4: Testing generated content API...')
    try {
      const response = await fetch('http://localhost:3000/api/blogs/generated')
      if (response.ok) {
        const data = await response.json()
        console.log(`✅ Generated content API working. Found ${data.posts?.length || 0} AI-generated posts`)
        
        if (data.posts && data.posts.length > 0) {
          console.log('   Sample AI-generated posts:')
          data.posts.slice(0, 3).forEach((post: any, index: number) => {
            console.log(`   ${index + 1}. ${post.title}`)
            console.log(`      Category: ${post.category}, Published: ${post.isPublished}`)
            console.log(`      Quality Score: ${post.qualityScore || 'N/A'}%`)
          })
        }
      } else {
        console.log(`⚠️ Generated content API returned status: ${response.status}`)
      }
    } catch (error) {
      console.log(`⚠️ Generated content API test skipped (server may not be running): ${error}`)
    }

    // Test 5: Test content generation workflow
    console.log('\n🔄 Test 5: Testing content generation workflow...')
    
    // Create a test RSS item
    const testRSSItem = {
      title: 'Test Transfer News: Star Player Joins Big Club',
      description: 'This is a test transfer announcement with betting implications for our automation system',
      link: 'https://test-example.com/transfer-news-123',
      pubDate: new Date(),
      source: 'BBC Sport',
      category: 'transfer',
      keywords: ['transfer', 'player', 'football', 'betting']
    }

    console.log(`   Created test RSS item: "${testRSSItem.title}"`)
    console.log(`   Source: ${testRSSItem.source}, Category: ${testRSSItem.category}`)
    console.log(`   Keywords: ${testRSSItem.keywords.join(', ')}`)

    // Test 6: Check if we can create a test blog post
    console.log('\n✍️ Test 6: Testing blog post creation...')
    try {
      const testBlogPost = await prisma.blogPost.create({
        data: {
          title: 'Test AI-Generated Blog Post',
          slug: 'test-ai-generated-blog-post',
          excerpt: 'This is a test blog post generated by our automation system',
          content: '<p>This is a test blog post content with some <strong>HTML formatting</strong> and multiple paragraphs.</p><p>It should demonstrate that our automation system can create properly formatted content.</p>',
          author: 'SnapBet AI Team',
          category: 'testAnalysis',
          tags: ['test', 'automation', 'blog'],
          geoTarget: ['worldwide'],
          featured: false,
          readTime: 2,
          seoTitle: 'Test AI-Generated Blog Post - SnapBet AI',
          seoDescription: 'This is a test blog post generated by our automation system to verify functionality',
          seoKeywords: ['test', 'ai', 'automation', 'blog'],
          isPublished: false,
          aiGenerated: true,
          sourceUrl: 'https://test-example.com/test-article'
        }
      })

      console.log(`✅ Test blog post created successfully!`)
      console.log(`   ID: ${testBlogPost.id}`)
      console.log(`   Title: ${testBlogPost.title}`)
      console.log(`   AI Generated: ${testBlogPost.aiGenerated}`)
      console.log(`   Source URL: ${testBlogPost.sourceUrl}`)

      // Test 7: Test publishing the blog post
      console.log('\n📤 Test 7: Testing blog post publishing...')
      const publishedPost = await prisma.blogPost.update({
        where: { id: testBlogPost.id },
        data: {
          isPublished: true,
          publishedAt: new Date()
        }
      })

      console.log(`✅ Blog post published successfully!`)
      console.log(`   Published: ${publishedPost.isPublished}`)
      console.log(`   Published At: ${publishedPost.publishedAt}`)

      // Test 8: Clean up test data
      console.log('\n🧹 Test 8: Cleaning up test data...')
      await prisma.blogPost.delete({
        where: { id: testBlogPost.id }
      })
      console.log(`✅ Test blog post deleted successfully`)

    } catch (error) {
      console.log(`❌ Blog post creation test failed: ${error}`)
    }

    // Test 9: Check automation statistics
    console.log('\n📊 Test 9: Checking automation statistics...')
    const stats = await prisma.blogPost.groupBy({
      by: ['aiGenerated', 'isPublished'],
      _count: {
        id: true
      }
    })

    console.log('   Blog post statistics:')
    stats.forEach(stat => {
      const type = stat.aiGenerated ? 'AI-Generated' : 'Manual'
      const status = stat.isPublished ? 'Published' : 'Draft'
      console.log(`   - ${type} ${status}: ${stat._count.id}`)
    })

    console.log('\n✅ All blog automation tests completed successfully!')
    console.log('\n📋 Summary:')
    console.log('   ✅ Database schema updated with aiGenerated and sourceUrl fields')
    console.log('   ✅ Blog post creation and publishing workflow working')
    console.log('   ✅ API endpoints ready for testing (when server is running)')
    console.log('   ✅ Content generation workflow ready for RSS integration')
    
  } catch (error) {
    console.error('❌ Test failed:', error)
  } finally {
    await prisma.$disconnect()
  }
}

// Run the test
testBlogAutomationSystem().catch(console.error) 