/**
 * Deterministic FAQ blocks per hub type. Rendered both as visible Q&A
 * cards and as FAQPage JSON-LD for Google rich-results eligibility.
 *
 * Voice rules (consistent with /methodology + tracker card):
 *  - Neutral expert tone
 *  - No "guaranteed", "lock", "100% accuracy"
 *  - Anchor specifics in real data we surface elsewhere
 */

export interface FAQEntry {
  question: string
  answer: string
}

export function dailyHubFAQ(dayName: 'today' | 'tomorrow'): FAQEntry[] {
  const dayLabel = dayName === 'today' ? "today's" : "tomorrow's"
  return [
    {
      question: `How are ${dayLabel} soccer predictions generated?`,
      answer:
        `Each fixture runs through two independent models: V1 (consensus statistical) and V3 (Sharp Intelligence — a 90-day fresh-era model that adapts to current form). We surface the model's pick (home, draw, or away) along with its confidence score and the average market odds at the time we captured it. Full methodology lives at /methodology.`,
    },
    {
      question: `What is the model's recent hit rate?`,
      answer:
        `We publish live audited results — every win and loss — at /performance, our flat-$100 simulation tracker. We don't bake hit-rate claims into static copy; check the tracker for the current numbers. Past performance does not guarantee future results.`,
    },
    {
      question: `What does "high-confidence pick" mean here?`,
      answer:
        `A fixture appears in the top-picks list when at least one of our two models reports a confidence of 50% or higher for a specific outcome. Picks above 60% on V3 in particular have historically been the strongest tier — see the tracker breakdown on /performance.`,
    },
    {
      question: `Are these predictions free?`,
      answer:
        `Yes. Today's and tomorrow's prediction surfaces, league breakdowns, head-to-head data, and the public performance audit are all free. Premium picks unlock additional analysis and the higher-conviction tier; you can preview the tracker's premium-only performance at /performance.`,
    },
    {
      question: `Where do the odds come from?`,
      answer:
        `Odds are aggregated across multiple bookmakers into a single consensus probability per outcome. We translate the consensus back into decimal odds for display. When a pick enters our premium tracker, the odds at the time of capture are locked in — that's how the flat-$100 simulation stays auditable.`,
    },
    {
      question: `What if a match doesn't have a high-confidence pick?`,
      answer:
        `The model surfaces a no-bet signal more often than people expect — we'd rather pass than push a low-conviction call. Matches without a meaningful pick still appear in the full fixtures list below, but they don't make the top-picks shortlist.`,
    },
  ]
}

export function leagueHubFAQ(leagueName: string): FAQEntry[] {
  return [
    {
      question: `How accurate are SnapBet's ${leagueName} predictions?`,
      answer:
        `Each ${leagueName} prediction is generated by two models (V1 and V3). The recommended model per team is shown on each team's page at /team/{slug}/predictions. Aggregate accuracy by league is visible inside each team page's stats card. Live audited results at /performance.`,
    },
    {
      question: `When are ${leagueName} fixtures updated?`,
      answer:
        `Fixtures are synced upstream every few hours and rolled into the page within a 5-minute cache window. Predictions are generated as availability permits — sometimes a match's V3 prediction lands closer to kickoff as more data accumulates.`,
    },
    {
      question: `Are these predictions personalized to my country?`,
      answer:
        `The model itself is global — predictions and odds don't change by user location. Country-specific surfaces (currency, payment methods) live under /[country] routes; the underlying predictions are the same.`,
    },
    {
      question: `Where can I see ${leagueName} team-level analysis?`,
      answer:
        `Each ${leagueName} club with sufficient history (≥10 finished matches in our window plus recent activity) has a dedicated /team/{slug}/predictions page with form, model accuracy, H2H against frequent opponents, and a quarterly-refreshed AI-written profile.`,
    },
  ]
}
